### ISSUE TITLE
rsocket channels - publishOn sometimes doesn't cause next operators to run on scheduler 

### ISSUE THREAD

**Issue by asiab1** [rsocket/rsocket-java#827] opened 2020-05-08 11:18 UTC
Context:
Rsocket SpringBoot + JS
Some of the endpoints are prepared in a channel model. Frontend side uses rsocket-flowable to prepare publisher and then uses it to send data to the server. 

Method which transforms this stream and returns another one looks like this:

```
public Flux<Data> basicData(Flux<Address> address) {
        final AtomicReference<Address> observed= new AtomicReference<>();
        final Scheduler dataScheduler = Schedulers.newSingle("basic-data");

        return address
                .onBackpressureLatest()
                .doOnNext(observed::set)
                .publishOn(dataScheduler, 1)
                .mergeWith(changes)
                .map(address -> Pair.of(address, getData(address)))
                .filter(p -> p.getKey().equals(observed.get()))
                .map(Pair::getRight)
                .distinctUntilChanged();
    }
```

**address** flux is supposed to deliver currently observed element to get updates when it's value changes. **changes** flux is supposed to deliver any changes which happen (TopicProccessor).

We have some endpoints like this one. 
I have observed very weird behaviour. Usually publishOn causes next operators to run on the scheduler, but not always. Sometimes whole stream is run on the main thread what causes thread block and (for example) keep-alive requests not getting to the point.

Extra info: after adding _doOnNext_ between _publishOn_ and _mergeWith_ operators, described situation doesn't appear.

Is there any explanation for this?

**Comment by OlegDokuka** [comment] 2020-05-08 11:22
Hey @asiab1!

Thanks for sharing your findings. 
Can you please provide a few answers:
  1. What version do you use?
  2. Does it reproduce without RSocket but with the similar conditions?
  3. Do you have any samples in the isolations to reproduce this issue if it is strictly related to RSocket?

Cheers,
Oleh

**Comment by asiab1** [comment] 2020-05-08 12:32
Hi! Thank you for your quick response.

1. 1.0.0-RC6
2. I tried to reproduce it in tests when using the same set of operators, but without such effects. 
3. Unfortunately at this moment I have no any isolated samples. I would need some time to prepare such.

I add log() operators between _doOnNext_ and _publishOn_ and between _mergeWith_ and _map_ and here are the logs:

normal behaviour:
```
2020-05-08 11:49:02 [reactor-http-epoll-4] INFO  reactor.Flux.Merge.34                    : onSubscribe(FluxFlatMap.FlatMapMain)
2020-05-08 11:49:02 [reactor-http-epoll-4] INFO  reactor.Flux.Merge.34                    : request(1)
2020-05-08 11:49:02 [reactor-http-epoll-4] INFO  reactor.Flux.Peek.33                     : onSubscribe(FluxPeek.PeekSubscriber)
2020-05-08 11:49:02 [reactor-http-epoll-4] INFO  reactor.Flux.Peek.33                     : request(1)
2020-05-08 11:49:02 [reactor-http-epoll-4] INFO  reactor.Flux.Peek.33                     : onNext([someData])
2020-05-08 11:49:02 [basic-data-37] INFO  reactor.Flux.Peek.33                     : request(1)
2020-05-08 11:49:02 [basic-data-37] INFO  reactor.Flux.Merge.34                    : onNext([someData])
```

weird behaviour:
```
2020-05-08 11:50:34 [reactor-http-epoll-1] INFO  reactor.Flux.Merge.36                    : onSubscribe(FluxFlatMap.FlatMapMain)
2020-05-08 11:50:34 [reactor-http-epoll-1] INFO  reactor.Flux.Merge.36                    : request(1)
2020-05-08 11:50:34 [reactor-http-epoll-1] INFO  reactor.Flux.Peek.35                     : onSubscribe(FluxPeek.PeekSubscriber)
2020-05-08 11:50:34 [reactor-http-epoll-1] INFO  reactor.Flux.Peek.35                     : request(1)
2020-05-08 11:50:34 [reactor-http-epoll-1] INFO  reactor.Flux.Peek.35                     : onNext([someData])
2020-05-08 11:50:34 [reactor-http-epoll-1] INFO  reactor.Flux.Peek.35                     : request(1)
2020-05-08 11:50:34 [reactor-http-epoll-1] INFO  reactor.Flux.Merge.36                    : onNext([someData])
```

I've noticed, that after opening the connection everything by default is working on one thread (for example **reactor-htttp-epoll-1**. (We open the connection between backend and frontend once - and every request goes on this connection. Maybe it's the wrong way to do this?) That's why when our calculations happen on this thread, every other action is blocked (I've noticed this on keep-alive, because it's the easiest way to see this - keep-alive messages are sent all the time and sometimes front does not get the responses when something is happening).

**Comment by asiab1** [comment] 2020-05-08 12:43
I've also tried logging from inside getData(address) method and the same result - usually **basic-data-...** thread, but sometimes **reactor-http-epoll-...**

**Comment by OlegDokuka** [comment] 2020-05-08 13:45
First of all, there is no guarantee that `publishOn` will guarantee that changes will be run on the same thread as you `publishOn`. Because of racing, you may easily end up that after `mergeWith` everything will be processed on the different thread then you specified by `publishOn`.

> I add log() operators between doOnNext and publishOn and between mergeWith and map and here are the logs:

Better to see a code sample to explain where did you put logging in.

> That's why when our calculations happen on this thread, every other action is blocked

hah, that is the reason. And the rootcause, I don't have a full picture but I suspect that `.mergeWith(changes)` comes from RSocket `requestStream`|`requestChanne` or soo, which means that you are scheduling only

`Flux<Address> address` on the specific thread, but it does not affect the `changes` stream anyhow.

**Comment by asiab1** [comment] 2020-05-08 14:06
To be clear - changes stream doesn't come from rsocket - it's output of TopicProcesor created by us. And described situation happens ONLY for events comming from front (**Flux\<Address\> address**). No event was published by **changes** at that moment.

And here is the code with added log operators:

```
return address
                .onBackpressureLatest()
                .doOnNext(observed::set)
                .log()
                .publishOn(dataScheduler, 1)
                .mergeWith(changes)
                .log()
                .map(address -> Pair.of(address, getData(address)))
                .filter(p -> p.getKey().equals(observed.get()))
                .map(Pair::getRight)
                .distinctUntilChanged();
```

**Comment by OlegDokuka** [comment] 2020-05-08 14:10
So, to clarify...

you say that if you write something like 

```
address
                .onBackpressureLatest()
                .doOnNext(observed::set)
                .publishOn(dataScheduler, 1)
                .log()
                .mergeWith(changes)
                .map(address -> Pair.of(address, getData(address)))
                .filter(p -> p.getKey().equals(observed.get()))
                .map(Pair::getRight)
                .distinctUntilChanged();
```

it is going to mix different, is it correct? (just double checking)

Also, can you try to repro the same with RC-7, just to make sure we have that issue still?


Cheers,
Oleh

**Comment by asiab1** [comment] 2020-05-11 12:21
If I add log() after publishOn() (like in your example code) it will behave as expected - publishOn works and changes thread to the one from scheduler. 

Upgrading rsocket to RC-7 unfortunately didn't make any change. 

I've finally found the solution in this case which seems to work. It looked like the problem occurs between publishOn() and merge() so I tried to move publishOn() after merge(). It now looks like this:

```
Flux.merge(
                   1,
                   address
                       .onBackpressureLatest()
                       .doOnNext(observed::set),
                  changes
                       .onBackpressureBuffer(Queues.SMALL_BUFFER_SIZE, BufferOverflowStrategy.DROP_OLDEST)
           )
                .publishOn(dataScheduler, 1)
                .map(address -> Pair.of(address, getData(address)))
                .filter(p -> p.getKey().equals(observed.get()))
                .map(Pair::getRight)
                .distinctUntilChanged();
```
I had to use static merge() with prefetch set to 1 to get onBackpressureLatest() working on address stream.

**Comment by asiab1** [comment] 2020-05-11 13:50
If you would like to analize this issue anyway, here are logs with stack from both situations - expected one and the second, when publishOn is not "used". I hope it will be helpful.

Logs refer to app run with rsocket version RC-7 and this piece of code:

```
address
                .subscribeOn(Schedulers.elastic())
                .onBackpressureLatest()
                .doOnNext(observed::set)
                .publishOn(dataScheduler, 1)
                .mergeWith(changes)
                .map(address -> Pair.of(address, getData(address)))
                .filter(p -> p.getKey().equals(observed.get()))
                .map(Pair::getRight)
                .distinctUntilChanged();
```
expected:

```
reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:199)
 reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:704)
 reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
 reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:986)   
 reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runBackfused(FluxPublishOn.java:483)
 reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:520)
 reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
 reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
```

publishOn not working:

```
 reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:199)
 reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:704)
 reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
 reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:457)      
 reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:137)
 reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:99)
 reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
 reactor.core.publisher.FluxMerge.subscribe(FluxMerge.java:69)
 reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
 org.springframework.messaging.handler.invocation.reactive.ChannelSendOperator.subscribe(ChannelSendOperator.java:85)
 reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
 reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
 reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
 reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
 reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
 reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:247)
 reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:329)
 reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173)
 reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2317)
 reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132)
 reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:318)
 reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:145)
 reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
 reactor.core.publisher.Mono.subscribe(Mono.java:4218)
 reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
 reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
 reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
 reactor.core.publisher.Mono.subscribe(Mono.java:4218)
 reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207)
 reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
 reactor.core.publisher.Flux.subscribe(Flux.java:8325)
 reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.onNext(FluxSwitchOnFirst.java:154)
 reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
 reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
 reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:495)
 reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:247)
 reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:324)
 reactor.core.publisher.UnicastProcessor.subscribe(UnicastProcessor.java:443)
 reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
 reactor.core.publisher.FluxPublishOn.subscribeOrReturn(FluxPublishOn.java:91)
 reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:55)
 io.rsocket.core.RSocketResponder.handleStream(RSocketResponder.java:512)
 io.rsocket.core.RSocketResponder.handleChannel(RSocketResponder.java:557)
 io.rsocket.core.RSocketResponder.handleFrame(RSocketResponder.java:315)
 reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
 reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
 reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554)
 reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630)
 reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.onNext(FluxGroupBy.java:670)
 reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:205)
 reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
 reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
 reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
 reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:220)
 reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:354)
 reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:352)
 reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:493)
 reactor.netty.http.server.WebsocketServerOperations.onInboundNext(WebsocketServerOperations.java:154)
 reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
 io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
 io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
 io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
 io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
 io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
 io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.lang.Thread.run(Thread.java:748)
```

**Comment by OlegDokuka** [comment] 2020-05-11 16:09
After all, I believe that there is a misunderstanding about how Reactor should be using and I don't think that there are any issues related to RSocket_Java it selves.

I'm closing this issue as for now until there is proper reproduce of the exception which might be tested locally.

Feel free to reopen your issue when you have something to show.

Cheers,
Oleh

**Closed by OlegDokuka** 2020-05-11 16:09 UTC
