### ISSUE TITLE
Metadata-pushes rate is not capped on responder, may lead to server resources starvation

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-java#865] opened 2020-06-12 14:31 UTC
External clients can start hundreds of thousands of metadata-pushes over multiple connections.

If metadata-push handler is present and It does not implement rate limiting on its own, then server is subject to resource starvation attack.

If metadata-push handler is absent, then [exception with stacktrace](https://github.com/rsocket/rsocket-java/blob/9e12fb35a906e6d6fffeaa9197d2d8138f11031b/rsocket-core/src/main/java/io/rsocket/RSocket.java#L83) is created for every metadata-push - this just consumes cpu cycles. With sufficiently large number of metadata-pushes RSocket becomes unresponsive.

Problem worsens with websocket transport of  this repository. By default It [sets](https://github.com/rsocket/rsocket-java/blob/9e12fb35a906e6d6fffeaa9197d2d8138f11031b/rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java#L54) frame size limit to  ~16MB - this opens opportunity for memory overflow given there may be arbitrarily large number of concurrent metadata-pushes with size close to said size limit.

**Comment by OlegDokuka** [comment] 2020-06-12 14:58
Hey!

First of all, **we appreciate issues and bug reports**! 

**However**, sometimes it is **_HARD_** to figure out what the issue is about. In certain: **how to reproduce it**; **what is the root cause**; **what is possible solutions to mitigate it**!  

Having no such info just makes it **challenging** for maintainers to help submitter / improve project by resolving the issue.
 
_**Therefore**_, we created issues' templates for that purpose so the issue submitter can express all important points that maintainers need in order to resolve an issue. Otherwise, if thoughts were not expressed clearly just make the issue useless and waste maintainers' time on figuring out what was said. 

**Therefore, please respect maintainers if you submitting an issue!**

Thanks in advance.

-----

1. Any code samples to reproduce that? 

2. I believe the same issue can happen with fnf call. Is not it?

3. **_The issue is not critical and a workaround for everything lower than 1.0.2  will be overriding of all RSocket methods with a static response error_**

4. The solution for this issue will be creating static Mono.error/Flux.error for `RSocket.class` so stack trace will not be filled on every call.

5.
> Problem worsens with websocket transport of this repository. By default It sets frame size limit to ~16MB - this opens opportunity for memory overflow given there may be arbitrarily large number of concurrent metadata-pushes with size close to said size limit.

The same as for point 1 - any code that reproduces that, or is it just a theoretical assumption that has no proof? 

On the `RSocketRequester` side we have `Payload` [validation](https://github.com/rsocket/rsocket-java/blob/9e12fb35a906e6d6fffeaa9197d2d8138f11031b/rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java#L597) which ensures that payload is not overdue 16 content size. That said it is impossible to send frame bigger than 16 MB -> since [validation code](https://github.com/rsocket/rsocket-java/blob/9e12fb35a906e6d6fffeaa9197d2d8138f11031b/rsocket-core/src/main/java/io/rsocket/core/PayloadValidationUtils.java#L16) ensures that frame size is less or equal to 16MB (total sum of headers and content)

Cheers,
Oleh

**Comment by rstoyanchev** [comment] 2020-07-27 07:41
I think metadata pushes are not meant to be used for sending a lot of data or to be sent very frequently. We can add some basic rate limiting mechanism that allows up a certain number of pushes and/or metadata size within some period of time. That can be much lower than the general 16 MB frame size from the spec.

**Closed** 2020-09-24 14:53 UTC
Labels: needs information
