### ISSUE TITLE
reactivesocket -> rsocket

### ISSUE THREAD

**Issue by benjchristensen** [rsocket/rsocket-java#268] opened 2017-04-05 16:38 UTC
What will it take to allow moving this repo to github.com/rsocket/rsocket-java?

I imagine it is:

- Maven Central config
- BinTray config
- Travis config
- package change in all source files

If I help with the changes above, any reason to not proceed?

**Comment by viktorklang** [comment] 2017-04-10 10:50
I guess the biggest reason not to is the prior art (names)

https://www.google.se/search?q=rsocket

(ReactiveSocket comes up this as its first hit)

**Comment by yschimke** [comment] 2017-05-07 09:12
@benjchristensen snapshots are broken at the moment

Deploying artifact: https://oss.jfrog.org/oss-snapshot-local/io/rsocket/rsocket-client/0.9-SNAPSHOT/rsocket-client-0.9-SNAPSHOT-javadoc.jar

Caused by: java.io.IOException: Failed to deploy file: HTTP response code: 403. HTTP response message: Forbidden

**Comment by yschimke** [comment] 2017-05-08 10:45
Travis Build link is also broken https://github.com/ReactiveSocket/reactivesocket-java

I've reverted that until we rename the top level repository also

https://github.com/ReactiveSocket/reactivesocket-java/commit/9a96d26920e45346b72458267b3ccf6ff3a306b9

**Comment by mitermayer** [comment] 2017-05-08 18:21
Is this blocking a releases for 1.0.x branch ?

**Comment by yschimke** [comment] 2017-05-08 18:36
I assume so. But don't know for sure. Eg release publishing must be diff repo

**Comment by yschimke** [comment] 2017-05-11 18:46
@benjchristensen I currently don't have write access to https://github.com/rsocket/rsocket-java/ is that related to the move?

**Comment by robertroeser** [comment] 2017-05-18 02:10
@benjchristensen Can we close this or do we need to up the travis build?

**Comment by yschimke** [comment] 2017-05-18 07:31
I put back the Travis build link but it's still failing to publish these artifacts (403 error)

**Closed** 2017-05-31 06:11 UTC
