### ISSUE TITLE
LoadBalancedRSocketMono refresh problem after new Collection<RSocketSupplier>

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket-java#634] opened 2019-05-16 01:23 UTC
Steps as following: 

* create a rsocketSupplierProcessor with initial RSocket cluster information
* create LoadBalancedRSocketMono from rsocketSupplierProcessor
* invoke  rsocketSupplierProcessor.onNext()  to  update RSocket cluster information 

LoadBalancedRSocketMono will not work after cluster information updated. Maybe refreshSockets() not invoked after cluster updated.  

```
        // rsocket cluster
        List<String> uriList1 = Arrays.asList("tcp://127.0.0.1:42252");
        ReplayProcessor<List<RSocketSupplier>> rsocketSupplierProcessor = ReplayProcessor.cacheLast();
        rsocketSupplierProcessor.onNext(uriList1.stream().map(uri -> new RSocketSupplier(() -> rSocket(uri))).collect(Collectors.toList()));
        LoadBalancedRSocketMono rSocketMono = LoadBalancedRSocketMono.create(rsocketSupplierProcessor);
        //update rsocket cluster,  the update logic in io.rsocket.client.RSocketSupplierPool.handleNewFactories
        // handleNewFactories does not invoke io.rsocket.client.LoadBalancedRSocketMono.refreshSockets();
        List<String> uriList2 = Arrays.asList("tcp://localhost:42252");
        rsocketSupplierProcessor.onNext(uriList2.stream().map(uri -> new RSocketSupplier(() -> rSocket(uri))).collect(Collectors.toList()));
       
```

**Comment by robertroeser** [comment] 2019-05-16 04:15
Is this a duplicate of #633 ?

**Comment by jareddellitt** [comment] 2019-05-21 18:46
I think this is the same thing I addressed in #623.

**Comment by robertroeser** [comment] 2019-05-28 06:37
@jareddellitt @linux-china 0.12.2-RC3 is out

**Comment by linux-china** [comment] 2019-05-28 20:10
@robertroeser  yes, it works for me with 0.12.2-RC3  :)

**Closed** 2019-05-29 06:44 UTC
