### ISSUE TITLE
RSocket server randomly throws java.lang.IllegalArgumentException when using ssl

### ISSUE THREAD

**Issue by EvanGuoBin** [rsocket/rsocket-java#734] opened 2020-01-15 11:19 UTC
Hi, I’m using spring messaging and ssl handler has been enabled. However, the server randomly throws exception below:
```
java.lang.IllegalArgumentException: promise already done: DefaultChannelPromise@77eb9d51(failure: java.lang.UnsupportedOperationException)
	at io.netty.channel.AbstractChannelHandlerContext.isNotValidPromise(AbstractChannelHandlerContext.java:891) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:773) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.ssl.SslHandler.finishWrap(SslHandler.java:899) ~[netty-handler-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:885) ~[netty-handler-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:797) ~[netty-handler-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:778) ~[netty-handler-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at reactor.netty.channel.MonoSendMany$SendManyInner$AsyncFlush.run(MonoSendMany.java:621) ~[reactor-netty-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

It has bothered me for a long time. When I debug into the source code, I just found that:
![image](https://user-images.githubusercontent.com/42926958/72429218-65db1700-37ca-11ea-874e-822808f068dd.png)

When `toReturn` is null, `composeFirst` will be invoked and `toReturn` will be assigned as a `Tuple2ByteBuf`. In this case (toReturn is not null) when `compose` is invoked, `Tuple2ByteBuf.writeBytes(next)` is called.

Since `Tuple2ByteBuf` is a subclass of `AbstractTupleByteBuf`, it does not implement `writeBytes`. Then `UnsupportedOperationException` is thrown.

What should I do to deal with this issue? Or is there anything I missed?

Many thanks!

**Comment by mostroverkhov** [comment] 2020-02-05 21:56
Library is using buggy custom `TupleByteBuf` implementation for outgoing frames, and unfortunately there is no option switch back to `CompositeByteBuf`. Any version after 0.12.2-RC4 until at least 1.0.0-RC5 is affected.

**Comment by OlegDokuka** [comment] 2020-02-06 10:24
Yes. I have to admit that there is such a noisy bug. The idea behind TuppleBB is to reduce number of allocation which gives about 10-15 percent performance win. I'm going to try to fix that but this week but for now, going to step back to compositebytebuf just to fix that bug

**Comment by OlegDokuka** [comment] 2020-03-06 18:09
@EvanGuoBin I went over the bug and was did my best to reproduce this issue, but unfortunately, I had no lack of doing that. Going over the `io.netty.handler.ssl.SslHandler.SslHandlerCoalescingBufferQueue` and debugging `io.netty.handler.ssl.SslHandler.SslHandlerCoalescingBufferQueue#compose` I found out that it is impossible to enter the tupleButeBuf write method.

Let's consider the following code sample.
[Netty-Handler 4.1.37]
```java
private static boolean attemptCopyToCumulation(ByteBuf cumulation, ByteBuf next, int wrapDataSize) {
        final int inReadableBytes = next.readableBytes();
        final int cumulationCapacity = cumulation.capacity();
        if (wrapDataSize - cumulation.readableBytes() >= inReadableBytes &&
                // Avoid using the same buffer if next's data would make cumulation exceed the wrapDataSize.
                // Only copy if there is enough space available and the capacity is large enough, and attempt to
                // resize if the capacity is small.
                (cumulation.isWritable(inReadableBytes) && cumulationCapacity >= wrapDataSize ||
                        cumulationCapacity < wrapDataSize &&
                                ensureWritableSuccess(cumulation.ensureWritable(inReadableBytes, false)))) {
            cumulation.writeBytes(next);
            next.release();
            return true;
        }
        return false;
    }
```

let's consider the case TupleByteBuf is a `cumulation` one.

1) `cumulation.isWritable(inReadableBytes)` always return false
2) It falbacks to 
```
 (cumulation.isWritable(inReadableBytes) && cumulationCapacity >= wrapDataSize ||
                        cumulationCapacity < wrapDataSize &&
                                ensureWritableSuccess(cumulation.ensureWritable(inReadableBytes, false)))
```

where `cumulation.ensureWritable(inReadableBytes, false)` always returns 3

so 
```
public static boolean ensureWritableSuccess(int ensureWritableResult) {
        return ensureWritableResult == 0 || ensureWritableResult == 2;
    }
```
returns false

3) the next attemtp
```
attemptCopyToCumulation(cumulation, next, wrapDataSize) ? cumulation :
                    copyAndCompose(alloc, cumulation, next);
```

goes to false branch so we execute  
`copyAndCompose(alloc, cumulation, next)`

which 
```
protected final ByteBuf copyAndCompose(ByteBufAllocator alloc, ByteBuf cumulation, ByteBuf next) {
        ByteBuf newCumulation = alloc.ioBuffer(cumulation.readableBytes() + next.readableBytes());
        try {
            newCumulation.writeBytes(cumulation).writeBytes(next);
        } catch (Throwable cause) {
            newCumulation.release();
            safeRelease(next);
            throwException(cause);
        }
        cumulation.release();
        next.release();
        return newCumulation;
    }
```

returns new byteBuf

**Comment by OlegDokuka** [comment] 2020-03-06 18:10
@EvanGuoBin I would appreciate if you can provide a code sample which can reproduce your case

**Comment by EvanGuoBin** [comment] 2020-03-11 06:54
Sorry for missing the comments because I've been busy recently.

This case cannot be stably reproduced. 

The situation is,

when I start up my application, everything goes well. However, application throws this exception after running for a certain time.(usually one day).

May i have your email  for further discussion and demo ?

**Comment by EvanGuoBin** [comment] 2020-03-11 07:04
My netty version is 4.1.39.Final

**Comment by EvanGuoBin** [comment] 2020-03-11 07:37
I've looked into the src code again and have a few questions.

![image](https://user-images.githubusercontent.com/42926958/76392209-09e8d500-63ac-11ea-8523-488cbb9d407b.png)

we can see that ```cumulation.ensureWritable(inReadableBytes, false)``` return ```0``` instead of ```3``` as expected.

In ```AbstractTupleByteBuf.java```:

![image](https://user-images.githubusercontent.com/42926958/76392353-546a5180-63ac-11ea-91c6-eb81a75c5ea9.png)

This method always returns 0 and ```Typle2ByteBuf.java``` doesn't override it.

Why ```cumulation.ensureWritable(inReadableBytes, false)``` always returns 3 according to your comments? Did I miss some key points?

**Comment by OlegDokuka** [comment] 2020-03-11 08:44
@EvanGuoBin indeed. That was fixed in the latest release (use RC6 if it is possible). 

Now I see why it works for me.

**Comment by EvanGuoBin** [comment] 2020-03-11 08:49
Yep, this issue was raised before RC6.

**Comment by OlegDokuka** [comment] 2020-04-05 08:41
@EvanGuoBin I rolled back to composite bytebuf and the optimized version of composite bytebuf will lend to netty-buffers directly

**Closed by OlegDokuka** 2020-04-05 08:41 UTC
Labels: bug
