### ISSUE TITLE
The channels were never completed on socket disposal prior to rsocket 1.1.0

### ISSUE THREAD

**Issue by SerCeMan** [rsocket/rsocket-java#956] opened 2020-11-04 08:43 UTC
Hey, folks!

This might be more of a behaviour question than an actual bug. However, I'm not 100% sure so I would like to clarify the expected behaviour. Consider the following code where the client requests a channel and then closes the connection. 

```java
import io.rsocket.*;
import io.rsocket.core.*;
import io.rsocket.transport.netty.client.TcpClientTransport;
import io.rsocket.transport.netty.server.TcpServerTransport;
import io.rsocket.util.*;
import reactor.core.publisher.*;
import java.util.concurrent.CountDownLatch;

public class Main {
  public static void main(String[] args) throws InterruptedException {
    var latch = new CountDownLatch(1);
    RSocketServer.create( //
        SocketAcceptor.forRequestChannel(source -> {
          var in = Flux.from(source)
              .doOnSubscribe(s -> System.out.println("subscribed to incoming"))
              .doOnCancel(() -> System.out.println("unsubscribed from incoming"))
              .doOnComplete(() -> System.out.println("complete incoming"))
              .doOnError(e -> System.out.println("error incoming: " + e.getClass()));
          var out = Flux.from(in);
          return out
              .doOnSubscribe(s -> {
                System.out.println("subscribed to outgoing");
                latch.countDown();
              })
              .doOnCancel(() -> System.out.println("unsubscribed from outgoing"))
              .doOnComplete(() -> System.out.println("complete outgoing"))
              .doOnError(e -> System.out.println("error outgoing: " + e.getClass()));
        }))
        .bind(TcpServerTransport.create(14242))
        .block();

    var client = RSocketConnector.create().connect(TcpClientTransport.create(14242)).block();
    var processor = DirectProcessor.<Payload>create();
    client.requestChannel(processor).subscribe();
    processor.onNext(ByteBufPayload.create(""));
    latch.await();
    client.dispose();

    Thread.currentThread().join();
  }
}
```

In the above example, rsocket `1.0.3` prints the following indicating that the subscription was cancelled but the channel did _not_ reach the terminal state (complete/error).
```
subscribed to incoming
subscribed to outgoing
unsubscribed from outgoing
unsubscribed from incoming
```

However, rsocket `1.1.0` prints the following indicating that all channels reached a terminal state when the subscription was cancelled.
```
subscribed to incoming
subscribed to outgoing
unsubscribed from outgoing
unsubscribed from incoming
error incoming: class java.util.concurrent.CancellationException
error outgoing: class java.util.concurrent.CancellationException
```

## Behavior

The behaviour in `1.1.0` seems to be the correct one. However, I couldn't find any related issues in the release notes, so just raising this issue to clarify whether my understanding is correct. If yes, I'm wondering whether there is a need to release a bugfix to the `1.0.x` branch or whether `1.0.x` is not supported anymore. Thanks :) 

## Steps to Reproduce

Running the above snippet. 

## Your Environment

* RSocket version(s) used: 1.0.3 and 1.1.0

**Comment by OlegDokuka** [comment] 2020-11-04 14:15
Hi @SerCeMan!

As usual, thank you for reporting that, indeed that a small point for improvement especially when it is a synchronous case. 

On the other hand, we propagate error in any case so if it happens to be a disconnected pipeline or a pipeline with something like a `.cancelOn` operator which offloads cancel signal on a different thread, in such scenario, you will see a `CancelledExceptrion` propagated from the upstream (which is expected since we can not guess if the pipe is connected or not.

your case should be fixed with #2e84405

**Comment by OlegDokuka** [comment] 2020-11-04 14:22
closing this one, let me know if you spot anything similar to that case

Oleh

**Comment by SerCeMan** [comment] 2020-11-04 22:31
Hey, @OlegDokuka! Thanks! Would you be able to clarify for my understanding of whether the behaviour of cancelling but not completing streams is correct? I'm trying to count the number of channels that went to a particular `RSocket` in a similar way to `io.rsocket.client.LoadBalancedRSocketMono.WeightedSocket.CountingSubscriber`, however, I'm struggling to understand how I can count it reliably since the streams are not guaranteed to be terminated.

**Comment by OlegDokuka** [comment] 2020-11-04 22:46
Hey @SerCeMan! What do you mean by canceling? Any relevant example? If that in the context of the issue, then there are 2 options for how to handle uncompleted streams:

1. Cancel Them; In case of everything but requestChannel that ends with normal cancellation signal. I the case of `requestChannel` this becomes a little tricky: In case of cancellation requestChannel on the responder side - the stream MUST be considered as terminated (due to spec) that say we have to terminate stream: by propagating a cancel signal through `Subscription#cancel` and to ensure that inbound stream's subscriber (e.g. `requestChannel(Flux<Payload inbound) { inboud.subscribe(inboundSubscriber);}` is notified - we have to propagate a cancelation error (the same behavior as you dispose a `Processor`).
2. Graceful shutdown, that is the second termination policy (and yes this one and the previous one are specified in the spec) where we have to wait for the termination of all active streams. Unfortunately, that strategy is not supported now, though in the high demand we can implement that one.

Regarding the loadbalance stuff. As you might notice, we have implemented loadbalancing from scratch -> https://github.com/rsocket/rsocket-java/blob/master/rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/loadbalancer/RoundRobinRSocketLoadbalancerExample.java, so now Loadbalancing is the core part of rsocket-core. Now, loadbalancing has a proper decoupling from rsocket management and the actual loadbalance strategy. That said, in theory - you can setup yours and count requests' stats up to your algorithm using `RequestInterceptor` interceptor in order to hook in on each request with-in an RSocket

**Comment by SerCeMan** [comment] 2020-11-04 23:22
> What do you mean by termination? Is it on the requester side?

On the responder side. I'm trying to count channels opened across a single RSocket in a way which is similar to the following class:

```java
static class CountingSubscriber<T> implements Subscriber<T> {
    static final AtomicInteger currentCount = new AtomicInteger(); // total number of channels
    final Subscriber<T> delegate; 

    CountingSubscriber(Subscriber<T> delegate) {
      this.delegate = delegate;
      new Thread(() -> {
        while (true) {
          System.out.println("Current channels: " + currentCount.get()); // print the current number
          try { Thread.sleep(1000L); } catch (Exception e) {}
        }
      }).start();
    }

    @Override
    public void onSubscribe(Subscription s) {
      currentCount.incrementAndGet();
      delegate.onSubscribe(s);
    }

    @Override
    public void onError(Throwable t) {
      currentCount.decrementAndGet();
      delegate.onError(t);
    }

    @Override
    public void onComplete() {
      currentCount.decrementAndGet();
      delegate.onComplete();
    }

    @Override
    public void onNext(T t) {
      delegate.onNext(t);
    }
  }
```

E.g. with the following acceptor. 
```
var acceptor = SocketAcceptor.forRequestChannel(in -> Flux.from(s -> in.subscribe(new CountingSubscriber<>(s))));
```

When the clients call `client.dispose()`, the `currentCount` doesn't get decremented prior to 1.1.0, however, it seems to count the number of channels correctly in 1.1.0 due to `java.util.concurrent.CancellationException`. So, I'm trying to understanding whether I can rely on the incoming streams on the responder side always reaching `complete`/`error` state.

**Comment by OlegDokuka** [comment] 2020-11-05 07:27
Gotcha. Let me take a look at 1.0.x to see if there is a bug

**Comment by OlegDokuka** [comment] 2021-03-02 10:29
@SerCeMan I remembered the root cause of why it does not work in 1.0.x as you expect it to work. The problem is in https://github.com/reactor/reactor-core/issues/2176. That said, in 1.0.x which depends on reactor 3.3.x, if the exception is racing with cancel, there is a chance that the error will be thrown back. Thus, when we know in advance that the cancel signal was received, we do not send any error. I aligned this behavior in 1.1.x so if we surely know that the inbound was canceled, we don't send anything, although 3.4.x relaxed error dropping behavior and does not throwback anything to the producer

**Comment by OlegDokuka** [comment] 2022-03-18 10:21
@SerCeMan should I close this one? Or do we expect this to be fixed in 1.0.x?

**Comment by SerCeMan** [comment] 2022-03-18 10:52
Hey, @OlegDokuka! I think this can be more of a gotcha rather than a bug, so can probably be closed.

**Comment by OlegDokuka** [comment] 2022-03-19 10:57
@SerCeMan thanks

**Closed by OlegDokuka** 2022-03-19 10:57 UTC
Labels: enhancement, minor
