### ISSUE TITLE
[Feature Request] Expose a custom exception serializer for developers to serialize/deserialize the ApplicationErrorException instances

### ISSUE THREAD

**Issue by JamesChenX** [rsocket/rsocket-java#896] opened 2020-07-27 03:18 UTC
## Motivation
To pass our business exceptions to the other side while avoid passing unnecessary exception data (In our cases, we just want to pass our business status code(Integer)), we have to use the message field (String) of the exceptions to implement our custom serialization and deserialization logic.
But it's error-prone and unfriendly to logger because the message is designed for serialization and deserialization and hard to read from the log.

## Desired solution
Expose a custom exception serializer for developers to serialize/deserialize the ApplicationErrorException instances.

The current serializer implementation is in io.rsocket.frame.ErrorFrameCodec#encode(io.netty.buffer.ByteBufAllocator, int, java.lang.Throwable)
```
  public static ByteBuf encode(ByteBufAllocator allocator, int streamId, Throwable t) {
    String message = t.getMessage() == null ? "" : t.getMessage();
    ByteBuf data = ByteBufUtil.writeUtf8(allocator, message);
    return encode(allocator, streamId, t, data);
  }
```
The pseudo code that we want:
```
  public static ByteBuf encode(ByteBufAllocator allocator, int streamId, Throwable t) {
        String message = t.getMessage() == null ? "" : t.getMessage();
        ByteBuf data;
        if (customSerializer != null && customSerializer.canSerialize(t)) {
            data = customSerializer.serialize(t);
        } else {
            data = ByteBufUtil.writeUtf8(allocator, message);
        }
        return encode(allocator, streamId, t, data);
  }
```
## Considered alternatives
No.

## Additional context
No.

**Comment by OlegDokuka** [comment] 2020-07-27 04:51
duplicate of #741

**Closed** 2020-07-27 04:51 UTC
Labels: duplicate
