### ISSUE TITLE
How to tell RSocket to read data stream by Java 8 Stream which backed by Blocking queue

### ISSUE THREAD

**Issue by vsaji** [rsocket/rsocket-java#964] opened 2020-12-14 13:35 UTC
I have the following scenario whereby my program is using blocking queue to process message asynchronously. There are multiple RSocket clients who wish to receive this message. My design is such a way that when a message arrives in the blocking queue, the stream that binds to the Flux will emit. I have tried to implement this requirement as below, but the client doesn't receive any response. However, I could see Stream supplier getting triggered correctly.

Can you pls help.
```
  @MessageMapping("addListenerHook")
public Flux<QueryResult> addListenerHook(String clientName){
    System.out.println("Adding Listener:"+clientName);
    BlockingQueue<QueryResult> listenerQ = new LinkedBlockingQueue<>();
    Datalistener.register(clientName,listenerQ);

    return Flux.fromStream(
            ()-> Stream.generate(()->streamValue(listenerQ))).map(q->{
        System.out.println("I got an event : "+q.getResult());
        return q;
    });
}


private QueryResult streamValue(BlockingQueue<QueryResult> inStream){
    try{
        return inStream.take();
    }catch(Exception e){
        return null;
    }
}
```

**Comment by yschimke** [comment] 2020-12-15 07:04
Dupe of https://stackoverflow.com/questions/65273027/how-to-tell-rsocket-to-read-data-stream-by-java-8-stream-which-backed-by-blockin

Let's answer over there instead of an in issue tracker.

**Closed by yschimke** 2020-12-15 07:04 UTC
Labels: question
