### ISSUE TITLE
Handling network errors in ClientServerInputMultiplexer

### ISSUE THREAD

**Issue by adrian-tarau** [rsocket/rsocket-java#815] opened 2020-05-04 16:04 UTC
We get these network failures logged as errors and they are not "errors" in some cases... If the other side stops, which the client still tries to communicate with it, you will get such errors.
It would be great if there would be some callback support here and there, where clients can decide what is worth logging as an error. 

```
2020-05-04 09:49:39,725 [RSocket-epoll-2] ERROR io.rsocket.FrameLogger - Error receiving frame: 
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

**Comment by OlegDokuka** [comment] 2020-05-04 16:14
Hey @adrian-tarau!

In RSocket we have an API `https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/RSocketFactory.java#L397`
which allows you to intercept such an error in general. 

In general `io.rsocket.FrameLogger` log path is used only for the debugging purpose and has never been designed to be a production logging system (if it is used as such in your case) 

Apart, you can always hook, intercept and log everything you really need in your app using Interceptor API https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/RSocketFactory.java#L454

@rstoyanchev do you think we need such common, configurable things in RSocket-Core library level apart from what we have today?

**Comment by adrian-tarau** [comment] 2020-05-04 16:16
It says "this is deprecated with no replacement" :)

**Comment by OlegDokuka** [comment] 2020-05-04 16:18
Outdated docs (as usual). We moved all connection errors propagation to `onClose` hook in the [new API](https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/Closeable.java#L35) which basically propagates terminal for current RSocket instance error over the `Subscriber#onError` API

**Comment by adrian-tarau** [comment] 2020-05-04 16:21
Great, thanks. I'll take a look at interceptors ...

**Comment by OlegDokuka** [comment] 2020-05-04 16:23
Sure, just let us know if you think that it should be implemented in a different way to keep developers work productive in the real-world applications

**Comment by adrian-tarau** [comment] 2020-05-04 16:25
Basically, I want network errors to be tracked, accounted, and "mark" and endpoint bad if it crosses a threshold. Events are retried in case of network errors, the client would not see these "glitches". Eventually, the client would get a CANCELED state of the other side is gone.

**Comment by OlegDokuka** [comment] 2020-05-04 16:27
Have you looked at a brightly new feature called [`reconnect`](https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java#L337)? It sounds pretty same as you wanna achieve

**Comment by adrian-tarau** [comment] 2020-05-04 16:31
let me add to it ... I want RSocket to inform be about anything that could not be delivered so I can make the decision on what to retry, when and if it cannot be delivered, track that and inform the client when a task failed because it cannot be processed.

**Comment by adrian-tarau** [comment] 2020-05-04 16:35
the reconnect is useful if the connection is lost ... for a short period of time ... I presume an error is not fired as long as it can re-connect? The problem that I want to solve is to not let RSocket decide when to log "issues". As a client, I'm creating a connection for each logical endpoint ... and if a failure occurs, I have the information to decide if the endpoint is offline (for whatever reason). Then I can tell the clients "task was canceled...it's not an issue, try later on"

**Comment by adrian-tarau** [comment] 2020-05-04 16:39
On top of this, I want to track errors, decide what to blacklist, for how long ... basically do not log errors because any LOGGER.error is tracked and reported and it just gives the wrong idea about the health of the system. There are counters tracking all sorts of "bad" events for this purpose. :)

**Comment by adrian-tarau** [comment] 2020-05-04 16:46
There is no need to log communication errors, those will be tracked in Grafana ... if an event fails, after all, retries, then we increase the counter associated with "undelivered event for event type". The client will handle these communication errors by rescheduling the task, etc ... but definitely not desired to see LOGGER.error for things that can be recovered, one way or another.

I actually upgraded from RC5 to RC7 and maybe I'm not doing the right way? Maybe even in RC5 I did not do the right thing?
Basically my setup on the client side is
```
Mono<RSocket> mono = RSocketFactory.connect()
                        .transport(TcpClientTransport.create(host, port))
                        .start();
                mono.doOnError(Throwable.class, throwable -> handleFailure(throwable, false))
                        .doOnDiscard(Object.class, this::handleDiscard)
                        .doOnTerminate(this::reportTermination);
                mono.subscribe(this::connectSuccessful, this::connectFailed, () -> {
                    LOGGER.info("Subscriber completed for " + getDescription());
                });
```

**Comment by OlegDokuka** [comment] 2020-05-04 16:51
Let me try to prepare a sample app for you

**Comment by adrian-tarau** [comment] 2020-05-04 17:12
Many thanks ... maybe it should be added to the home page, after "Trivial Client" ;)

**Comment by rstoyanchev** [comment] 2020-05-04 17:29
> Basically, I want network errors to be tracked, accounted, and "mark" and endpoint bad if it crosses a threshold. Events are retried in case of network errors, the client would not see these "glitches". Eventually, the client would get a CANCELED state of the other side is gone.

That sounds like the [reconnect feature](https://github.com/rsocket/rsocket-java/blob/c9a4f064ca1fe8fb06b67f7ac09ba2777bbb5634/rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java#L274-L336). The input `Retry` allows you to configure what that threshold is and when to give up.

> I want RSocket to inform be about anything that could not be delivered so I can make the decision on what to retry, when and if it cannot be delivered, track that and inform the client when a task failed because it cannot be processed

That is how it works. When the connection is lost, you still need to re-subscribe (i.e. some retry logic) in order to trigger a reconnect. See the Javadoc.

> There is no need to log communication errors, those will be tracked in Grafana 

As @OlegDokuka mentioned `io.rsocket.FrameLogger` category isn't meant for production. That said as far as I can tell, currently if you set `"io.rsocket"` to INFO, that will include errors from that logger unless you explicitly override its log level. So I think we need some explicit configuration flag to enable/disable frame logging (similar to Reactor Netty's `wiretap` property).

**Comment by adrian-tarau** [comment] 2020-05-04 21:45
@rstoyanchev I'll try the reconnect, thanks. 

Regarding logging, wiretap(true) actually changes the pipeline, and then you can play with logging. However, in this case, I have no control over enabling logging...it's always on.  Since LOGGER("io.rsocket.FrameLogger") always logs with ERROR level every time something goes wrong, the only option would be to set the logging level to FATAL for "io.rsocket.FrameLogger" ... which seems "wrong"?

**Comment by rstoyanchev** [comment] 2020-05-05 06:29
> Regarding logging, wiretap(true) actually changes the pipeline, and then you can play with logging. However, in this case, I have no control over enabling logging...it's always on. Since LOGGER("io.rsocket.FrameLogger") always logs with ERROR level every time something goes wrong, the only option would be to set the logging level to FATAL for "io.rsocket.FrameLogger" ... which seems "wrong"?

That's in line with my suggestion I think that frame logging should be off by default irrespective of log settings for "io.roscket". Once enabled explicitly (like wiretap) it can then be controlled with log settings. Perhaps also it should log consistently at DEBUG level.

**Comment by OlegDokuka** [comment] 2020-05-05 09:20
@adrian-tarau here is a sample app I prepared for you -> https://github.com/OlegDokuka/rsocket-reconnect-demo. Hope it shows the use-case and will help you adjust your code

**Comment by adrian-tarau** [comment] 2020-05-05 15:35
@rstoyanchev it is off by default, I did not enable it. Looking at the code, I do not see in any way how this LOGGER.error would not happen regardless of how RSocket/Reactor setup :)

The logger is created in ClientServerInputMultiplexer, created in RSocketConnection and RSocketServer and the exception is logged on errorConsumer ...unless the error is handled ahead, it will be logged.

Sorry if I ask/raise stupid questions, trying to read the code (examples) by myself and sometimes is not easy to grasp the big picture ;)

**Comment by adrian-tarau** [comment] 2020-05-05 15:50
@OlegDokuka thanks ... I'll integrate the retry part and simulate it in my context. But in the end, it still does not address my issue ... which is undesired logging of ERROR messages (or even WARN for that matter). I understand the retry will help with temporary connection issues and it would be transparent for the client, up to a point (number of retries).

However, as I tried to explain to @rstoyanchev I do not know a way to turn off all ERROR/WARN logging, rely on callbacks to be notified when something went wrong (usually network, marshaling, server side failures, etc). For everything other than network, everything goes well. I get an error, we the right exception, etc.

Let's say we have a service, in Docker, replicated, 10 instances. Start updating the stack, services stopped one by one and upgraded. The service is using a discovery mechanism in a registry (ZooKeeper) to notift peers when services are going down and coming up. And for most work, we can see when a node goes away and we will not schedule any work. However, in-flight events will fail, usually with "Connection reset by peer" or some other network error. Well, I would like not to log any error, tell clients "hey, your task was canceled, take a break and retry later"  and increment a counter (we have counters for successes, pending, failed, canceled). When the node comes back, maybe it comes back with a different address (usually the hostname is based on service name and slot, but it could be a new host), the pending tasks could be sent (with the new retry/reconnect) but some would really fail.

Buttom line, I want to get to no WARN/ERROR logging from RSocket (or Reactor) ... just tell me whenever something goes wrong and let me decide (in addition to whatever help I can get with internal retries/reconnects) what to do with the event.

**Comment by adrian-tarau** [comment] 2020-05-05 15:52
By "tell me" I mean RSocket, not you personally :)

**Comment by OlegDokuka** [comment] 2020-05-05 17:02
Can not you just put in logging config such as the [following](https://github.com/OlegDokuka/rsocket-reconnect-demo/blob/master/src/main/resources/logback.xml#L29)
to just turn off all the logs for 

```xml

    <!-- Set this to DEBUG to log frames -->
    <logger name="io.rsocket.FrameLogger" level="OFF"/>
```

**Comment by adrian-tarau** [comment] 2020-05-05 17:03
I can, but I was looking for a more elegant solution ;)

**Comment by OlegDokuka** [comment] 2020-05-05 17:05
Well. I believe I can do something like wiretap in reactor-netty to make stuff more elegant. 

Are you up for that @rstoyanchev ?

**Comment by rstoyanchev** [comment] 2020-05-06 05:15
@adrian-tarau I think you keep missing my point. I'm discussing a potential enhancement.

That said on a closer look, I don't think "wiretap" setting would solve anything. The `"io.rsocket.FrameLogger"` is already logging frames at DEBUG while the [log message](https://github.com/rsocket/rsocket-java/blob/c9a4f064ca1fe8fb06b67f7ac09ba2777bbb5634/rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java#L123) we're talking about is for an error on receiving (not for an ERROR frame).

In light of this, simply absorbing the error and closing quietly by default doesn't seem right. @adrian-tarau, I understand that you want to suppress network errors and that is your choice to configure in the logging config. I'm not sure why you say that is not elegant.

**Comment by OlegDokuka** [comment] 2020-05-06 06:02
I believe that the issue is to disable all the error logging since, as I understood it correctly, the auto-balancing is done based on the logs analysis. And, unfortunately, in order to disable all the logs from `ClientServerInputMultiplexer` we have to make `FrameLogger` to the level `off` because we have one place which going to be logging all the error 
https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java#L123

**Comment by adrian-tarau** [comment] 2020-05-06 12:50
@rstoyanchev Perfectly agree with the purpose of logging what's on the wire for RSocket ... however, if there is an error, one could expect to be notified on the doOnError? It should not be the role of the "logger" class ... I would think?

```
Mono<RSocket> mono = RSocketFactory.connect()
                       .......
                mono.doOnError(Throwable.class, throwable -> handleFailure(throwable, false))
```

**Comment by adrian-tarau** [comment] 2020-05-06 12:54
I'm perfectly fine suppressing these :) As long as I can make them disappear, all is good. I'm just trying to give my feedback/suggestion ... I think the client should be notified about these network errors (they are passed to doOnError, right? I did not check) and not logged automatically.

**Comment by OlegDokuka** [comment] 2020-05-06 15:24
I believe that we can improve that. Thus thanks a lot for sharing your vision @adrian-tarau !

**Comment by adrian-tarau** [comment] 2020-05-06 16:51
yeah, I would not call it vision ... but thank you ;)

**Comment by OlegDokuka** [comment] 2020-06-04 11:16
closing this one since it looks resolved

**Closed by OlegDokuka** 2020-06-04 11:16 UTC
Labels: question
